import './globals.css'
import { Metadata } from 'next'
import { Lexend } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const lexend = Lexend({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        {children}
        <Toaster position='bottom-right' />
      </body>
    </html>
  )
}

